name: update item model file

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python and Run
        uses: actions/setup-python@v2
        with:
          python-version: '3.6.9'
          architecture: x64
      - name: Install dependencies
        run: pip install pandas gspread oauth2client
      - name: Run Python
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID}}
          PRIVATE_KEY_ID: ${{ secrets.PRIVATE_KEY_ID}}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY}}
          CLIENT_EMAIL: ${{ secrets.CLIENT_EMAIL}}
          CLIENT_ID: ${{ secrets.CLIENT_ID}}
          CLIENT_X509_CERT_URL: ${{ secrets.CLIENT_X509_CERT_URL}}
          SPREADSHEET_KEY: ${{ secrets.SPREADSHEET_KEY}}      
        run: python update_model.py $PROJECT_ID $PRIVATE_KEY_ID $PRIVATE_KEY $CLIENT_EMAIL $CLIENT_ID $CLIENT_X509_CERT_URL $SPREADSHEET_KEY
      - name: Commit Files
        run: |
          git config user.name GitHub Actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config pull.rebase false
          git add .
          git commit -m "update model file"
          git pull
          git push origin main
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
